# Generated by Django 5.2 on 2026-08-22 01:43

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeanLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("earn", "شراء"),
                            ("bonus", "مكافأة"),
                            ("redeem", "استبدال"),
                            ("referral", "إحالة"),
                            ("signup", "تسجيل"),
                            ("expire", "انتهاء"),
                            ("adjust", "تعديل يدوي"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("balance_after", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateField(blank=True, db_index=True, null=True)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bean_ledger",
                        to="store.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bean_rows",
                        to="store.sale",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bean_ledger",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "base_manager_name": "unguarded",
                "indexes": [
                    models.Index(
                        fields=["store", "customer", "-created_at"],
                        name="store_beanl_store_i_79117e_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beans", models.IntegerField(db_index=True, default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("single", "سنجل"),
                            ("double", "دوبل"),
                            ("triple", "تريبل"),
                        ],
                        db_index=True,
                        default="single",
                        max_length=12,
                    ),
                ),
                ("tier_until", models.DateField(blank=True, null=True)),
                ("visits_this_month", models.PositiveIntegerField(default=0)),
                ("streak_weeks", models.PositiveIntegerField(default=0)),
                (
                    "last_visit_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to="store.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_profiles",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "base_manager_name": "unguarded",
                "indexes": [
                    models.Index(
                        fields=["store", "tier"], name="store_loyal_store_i_46f101_idx"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
    ]
