# Generated by Django 5.2 on 2026-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_beanledger_loyaltyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="customer",
            name="clerk_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
