# Generated by Django 5.2 on 2026-08-28 21:52

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_saleitem_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "بانتظار التأكيد"),
                            ("accepted", "تم القبول"),
                            ("preparing", "قيد التحضير"),
                            ("ready", "جاهز للاستلام"),
                            ("collected", "تم الاستلام"),
                            ("cancelled", "ملغى"),
                        ],
                        db_index=True,
                        default="placed",
                        max_length=16,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("cancelled_reason", models.CharField(blank=True, max_length=255)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="store.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="store.sale",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="store.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="store.productvariant",
                    ),
                ),
            ],
            options={
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="store.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order_placed", "تم إرسال الطلب"),
                            ("order_accepted", "تم قبول الطلب"),
                            ("order_preparing", "قيد التحضير"),
                            ("order_ready", "جاهز للاستلام"),
                            ("order_collected", "تم الاستلام"),
                            ("order_cancelled", "أُلغي الطلب"),
                            ("points_earned", "نقاط جديدة"),
                            ("points_spent", "استبدال نقاط"),
                            ("points_expiring", "نقاط على وشك الانتهاء"),
                            ("reward_unlocked", "مكافأة متاحة"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.CharField(blank=True, max_length=400)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="store.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
                "indexes": [
                    models.Index(
                        fields=["store", "customer", "-created_at"],
                        name="store_notif_store_i_d446ff_idx",
                    )
                ],
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "status", "created_at"],
                name="store_order_store_i_c164df_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("store", "client_uuid"), name="uniq_order_client_uuid"
            ),
        ),
    ]
