# Generated by Django 5.2 on 2026-08-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_order_orderitem_pushsubscription_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="beans_spent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfilment",
            field=models.CharField(
                choices=[("pickup", "استلام"), ("dinein", "على الطاولة")],
                db_index=True,
                default="pickup",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
