# Generated by Django 5.2 on 2026-09-02 20:59

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_sale_beans_spent"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="devicetoken",
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
    ]
