# Generated by Django 5.2 on 2026-10-04 04:45

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_devicetoken_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beanledger",
            name="rate_applied",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="EarnRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earn_rules",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["min_total", "position"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("key", models.CharField(blank=True, max_length=30)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("period", models.DateField(db_index=True)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="store.store",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="store.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("piece", "قطعة"), ("g", "غرام"), ("ml", "مل")],
                        default="piece",
                        max_length=8,
                    ),
                ),
                (
                    "purchase_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "purchase_unit",
                    models.CharField(
                        choices=[
                            ("piece", "قطعة"),
                            ("g", "غرام"),
                            ("kg", "كيلو"),
                            ("ml", "مل"),
                            ("l", "لتر"),
                        ],
                        default="piece",
                        max_length=8,
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("start_month", models.DateField()),
                ("end_month", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring",
                        to="store.expensecategory",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["category__position", "name"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_name", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cost_written_off",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("points_reversed", models.IntegerField(default=0)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_order", "خطأ في الطلب"),
                            ("taste", "الطعم"),
                            ("late", "تأخّر"),
                            ("spilled", "انسكب أو تلف"),
                            ("changed_mind", "غيّر رأيه"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="store.sale",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="store.saleitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_returns",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "wage_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "start"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("purchase", "شراء"),
                            ("waste", "هدر"),
                            ("count", "جرد"),
                            ("adjust", "تعديل"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "stock_after",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="store.inventoryitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_moves",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DemoMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=60)),
                ("object_pk", models.BigIntegerField()),
                ("restore", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
                "indexes": [
                    models.Index(
                        fields=["store", "model"], name="store_demom_store_i_6f8558_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "model", "object_pk"), name="uniq_demomark"
                    )
                ],
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="uniq_expcat_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                fields=("store", "client_uuid"), name="uniq_expense_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("store", "client_uuid"), name="uniq_invitem_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("store", "client_uuid"), name="uniq_return_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmove",
            constraint=models.UniqueConstraint(
                fields=("store", "client_uuid"), name="uniq_stockmove_client_uuid"
            ),
        ),
    ]
