# Generated by Django 5.2 on 2026-10-04 08:00

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_cafe_finance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "name"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("display_unit", models.CharField(blank=True, max_length=8)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "id"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="stockmove",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="receipt_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_moves",
                to="store.sale",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_moves",
                to="store.saleitem",
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchase", "شراء"),
                    ("waste", "هدر"),
                    ("count", "جرد"),
                    ("adjust", "تعديل"),
                    ("sale", "بيع"),
                    ("remake", "إعادة تحضير"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["store", "item", "created_at"],
                name="store_stock_store_i_a4fb5e_idx",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_categories",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="recipeline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_lines",
                to="store.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="recipeline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_lines",
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="recipeline",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_lines",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="recipeline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_lines",
                to="store.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycategory",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="uniq_invcat_name"
            ),
        ),
        migrations.AddIndex(
            model_name="recipeline",
            index=models.Index(
                fields=["product", "variant"], name="store_recip_product_c5f16d_idx"
            ),
        ),
    ]
