# Generated by Django 5.2 on 2026-10-09 14:33

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_expense_staff_payee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "base_manager_name": "unguarded",
                "default_manager_name": "unguarded",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "name"), name="uniq_supplier_name"
                    )
                ],
            },
            managers=[
                ("unguarded", django.db.models.manager.Manager()),
            ],
        ),
    ]
