# Generated by Django 5.2 on 2026-10-09 19:08

from decimal import ROUND_HALF_UP, Decimal

from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Every redemption so far was priced at the deployment rate — freeze
    that value onto the bill, so a later rate change cannot re-price it."""
    per = Decimal(int(getattr(settings, "POINTS_PER_ILS", 10)) or 10)
    for name in ("Sale", "Order"):
        Model = apps.get_model("store", name)
        for pk, spent in Model._base_manager.filter(beans_spent__gt=0).values_list("pk", "beans_spent"):
            value = (Decimal(spent) / per).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            Model._base_manager.filter(pk=pk).update(beans_value=value)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="beans_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="beans_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="points_per_ils",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
