# Generated by Django 5.2 on 2026-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_points_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card"), ("debt", "Debt")],
                db_index=True,
                default="cash",
                max_length=10,
            ),
        ),
    ]
